// This file is auto-generated by EliteHosting. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const elitehostingAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const elitehosting = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "elitehosting",
      opts?: SignInOptions,
    ) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result = await elitehostingAuth.signInWithOAuth(provider as any, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await (supabase.auth as any).setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
